### ISSUE TITLE
android.conf.in mentions inexisting binaries

### ISSUE THREAD

**Issue by dbuenzli** [whitequark/opam-android#10]
Given your [`Makefile.in`](https://github.com/whitequark/opam-android/blob/1223f7f64345596cc8baa1b99bb9927a63c85551/packages/ocaml-android32.4.02.3/files/config/Makefile.in), `ocamldoc` and `ocamlbuild` are not being build and as thus these [two](https://github.com/whitequark/opam-android/blob/1223f7f64345596cc8baa1b99bb9927a63c85551/packages/ocaml-android32.4.02.3/files/android.conf.in#L9-L10) lines of `android.conf.in` shouldn't be here.

**Comment by whitequark** [comment]
Sorry, I don't follow. You are mentioning `ocamldoc` and `ocamlbuild`, but the lines in `android.conf.in` are for `ocamldoc` and `ocamldep`. Furthermore, `ocamldep` is of course present.

`ocamldoc` is, indeed, not built.

**Comment by dbuenzli** [comment]
Yes sorry `ocamldoc` only I don't know where I got `ocamlbuild` idea from.

**Comment by whitequark** [comment]
Patch provided upstream as https://github.com/ocaml/ocaml/pull/251.
