### ISSUE TITLE
Need a complete example for calling ocaml code from android

### ISSUE THREAD

**Issue by whitehead1415** [whitequark/opam-android#3]
Could you add an example of calling ocaml code from android? Either in code or in the readme. I think the rest of the readme is really good I'm just not sure how to tie it all together when it comes to compiling with build-ndk.

**Comment by whitequark** [comment]
You'd invoke it like this (from some JNI function):
```
extern void caml_startup(char** args);
char* args[] = {NULL};
caml_startup(args);
```

**Comment by whitequark** [comment]
For more details you can see http://www.mega-nerd.com/erikd/Blog/CodeHacking/Ocaml/calling_ocaml.html.

**Comment by whitehead1415** [comment]
Thanks. The problem I was having was with my Android.mk that wasn't linking the ocaml libs

**Comment by whitequark** [comment]
I've never used ndk-build so I cannot help you. You can produce a final object file by passing `-output-obj -linkpkg -o foo.o`, or using the `foo.native.o` ocamlbuild target and applying the fix from [PR6625](http://caml.inria.fr/mantis/view.php?id=6625).

**Comment by whitequark** [comment]
It also might help to use the new flag `-output-complete-obj`, upcoming in 4.02.2 (http://caml.inria.fr/mantis/view.php?id=6797).
