### ISSUE TITLE
opam upgrade problem

### ISSUE THREAD

**Issue by markghayden** [whitequark/opam-android#6]
I've been successfully using 4.02.1 version of opal-android.  I'm trying to upgrade my 32-bit opam-android installation and running into a problem.  I'm building on a debian 64-bit install.  The host compiler is 4.02.1 32-bit, but opal-android seems to now require 4.02.2 32-bit.  I don't see a matching compiler listed by 'opam switch'.  Is there a trick to getting this to work?  The instructions seem out of date in that the refer to ocaml version 4.02.1.  Are there plans to upgrade to current 4.02.3 compiler?

thanks, Mark

```
debian64% opam upgrade
Everything as up-to-date as possible (run with --verbose to show unavailable
upgrades).
The following would require downgrades or uninstalls, but you may upgrade
them explicitly:
  - ocaml-android.4.02.2
debian64% opam install ocaml-android.4.02.2
The following dependencies couldn't be met:
  - ocaml-android -> ocaml-android32 = 4.02.2
Your request can't be satisfied:
  - ocaml-android32.4.02.2 is not available because your system doesn't comply with ocaml-version = "4.02.2" & arch = "x86" | compiler = "4.02.2+32bit".

No solution found, exiting
debian64% opam switch
--           -- 3.11.2        Official 3.11.2 release
--           -- 3.12.1        Official 3.12.1 release
--           -- 4.00.0        Official 4.00.0 release
--           -- 4.00.1        Official 4.00.1 release
--           -- 4.01.0        Official 4.01.0 release
--           -- 4.02.0        Official 4.02.0 release
4.02.1+32bit  C 4.02.1+32bit  4.02.1 compiled in 32-bit mode for 64-bit Linux and OS X hosts.
4.02.1        I 4.02.1        Official 4.02.1 release
--           -- 4.02.2        Official 4.02.2 release
--           -- 4.02.3        Official 4.02.3 release
system        I system        System compiler (4.00.0)
# 102 more patched or experimental compilers, use '--all' to show


debian64% 
```

**Comment by whitequark** [comment]
There is now: https://github.com/ocaml/opam-repository/pull/4815

**Comment by markghayden** [comment]
Thanks for the quick response.  It seems this has been fixed, but I'm not sure how to use the fix.  When I try to do an 'opam upgrade' after an update, it asks if I want to remove ocaml-android, which I don't think I want to do.  Are there specific steps I need to follow to do the upgrade?

thanks, Mark


debian64% opam update

=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[android] git://github.com/whitequark/opam-android already up-to-date
[default] synchronized from https://opam.ocaml.org
[WARNING] A conflict was detected in your installation. This can be caused by
          updated constraints or conflicts in your installed packages:
            - ocaml-android32 is not available because your system doesn't
          comply with
              ocaml-version = "4.02.3" & arch = "x86" | compiler =
          "4.02.3+32bit".


You should run "opam upgrade --fixup" to resolve the situation.
debian64% opam upgrade --fixup
The following actions will be performed:
  - remove yojson-android      1.2.0 
  - remove biniou-android      1.0.9 
  - remove easy-format-android 1.0.2 
  - remove ocaml-android       4.02.1
  - remove ocaml-android32     4.02.1
===== 5 to remove =====
Do you want to continue ? [Y/n] 
^Cdebian64% 
debian64%

**Comment by whitequark** [comment]
You do want to remove it, and then switch to `4.02.3+32bit`.
