### ISSUE TITLE
Failure on darwin

### ISSUE THREAD

**Issue by dbuenzli** [whitequark/opam-android#8]
```
/Users/dbuenzli/.opam/4.02.3+32bit/lib/android-ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86/bin/arm-linux-androideabi-ranlib: libcamlrun_pic.a: Malformed archive
# make[1]: *** [install-shared] Error 1
```

This is due to a hardcoded uses of `ar` see https://github.com/ocaml/ocaml/pull/249, could you maybe integrate the patch in the package ?

**Comment by whitequark** [comment]
Sure. Since I never encountered this error myself, could you test the opam-android switch with the patch present and send a PR?
